### ISSUE TITLE
Updating from 2.0.0-beta.15 to a higher version results in a composer dependency conflict

### ISSUE THREAD

**Issue by xhuang9** [dukt/social#29] opened 2019-03-04 05:24 UTC
### Description
Here is my composer error

Composer output: Package "craftcms/vue-asset" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Installation request for dukt/social 2.0.0-beta.16 -> satisfiable by dukt/social[2.0.0-beta.16].
- Conclusion: remove league/oauth2-google 2.2.0
- dukt/oauth2-google 2.0.0 requires league/oauth2-google ^2.0 -> satisfiable by league/oauth2-google[2.2.0, 2.1.0, 2.0.0, 2.0.1].
- dukt/oauth2-google 2.0.0 requires league/oauth2-google ^2.0 -> satisfiable by league/oauth2-google[2.2.0, 2.1.0, 2.0.0, 2.0.1].
- dukt/oauth2-google 2.0.0 requires league/oauth2-google ^2.0 -> satisfiable by league/oauth2-google[2.2.0, 2.1.0, 2.0.0, 2.0.1].
- Can only install one of: league/oauth2-google[2.2.0, 3.0.0].
- Can only install one of: league/oauth2-google[2.1.0, 3.0.0].
- Can only install one of: league/oauth2-google[2.0.0, 3.0.0].
- Can only install one of: league/oauth2-google[2.0.1, 3.0.0].
- Can only install one of: league/oauth2-google[3.0.0, 2.2.0].
- dukt/social 2.0.0-beta.16 requires league/oauth2-google ^3.0 -> satisfiable by league/oauth2-google[3.0.0, 3.0.1].
- Conclusion: don't install league/oauth2-google 3.0.1
- Installation request for dukt/oauth2-google (locked at 2.0.0) -> satisfiable by dukt/oauth2-google[2.0.0].

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.

### Additional info

- Plugin version:  2.0.0-beta.15 => 2.0.0-beta.16
- Craft version: Craft Pro 3.1.15
- PHP version: 7.1.25
- Database driver & version: MySQL 5.7.24

**Comment by benjamindavid** [comment] 2019-03-04 07:25
Hey @xhuang9, do you have any other plugins installed? Thank you.

**Comment by john-henry** [comment] 2019-03-04 22:09
@benjamindavid I get the same error. Here are my installed plugins

```
"craftcms/cms": "3.1.15",
    "vlucas/phpdotenv": "^2.4.0",
    "verbb/super-table": "2.1.15",
    "craftcms/redactor": "2.3.2",
    "dukt/social": "2.0.0-beta.15",
    "mmikkel/incognito-field": "1.1.1.1",
    "superbig/craft-entry-instructions": "1.0.4",
    "dukt/social-linkedin": "3.0.3",
    "solspace/craft3-freeform": "2.5.13",
    "ether/logs": "v3.0.0",
    "mikestecker/craft-videoembedder": "1.1.1",
    "enupal/snapshot": "1.2.2",
    "mmikkel/cp-clearcache": "1.0.3",
    "lukeyouell/craft-sidebarthemes": "1.0.5",
    "verbb/default-dashboard": "1.0.4",
    "adigital/cookie-consent-banner": "1.1.2",
    "nystudio107/craft-cookies": "1.1.11",
    "verbb/expanded-singles": "1.0.7",
    "johnhenry/pdf2email": "^1.0",
    "rias/craft-password-policy": "1.0.4",
    "barrelstrength/sprout-reports": "1.1.2",
    "bymayo/delete-account": "1.0.1",
    "bitboxde/minifier": "2.0.1",
    "superbig/craft3-http2serverpush": "1.0.1",
    "marionnewlevant/picture": "2.2.0",
    "putyourlightson/craft-campaign": "1.6.8",
    "putyourlightson/craft-campaign-pro": "1.0.0",
    "craftcms/mailgun": "1.4.2"
```

**Comment by xhuang9** [comment] 2019-03-04 23:14
Here is my composer.json  
"require": {
    "craftcms/cms": "3.1.15",
    "vlucas/phpdotenv": "^2.4.0",
    "pennebaker/craft-architect": "2.2.11",
    "verbb/super-table": "2.1.15",
    "fruitstudios/linkit": "1.1.8",
    "solspace/craft3-freeform": "2.5.13",
    "solspace/craft3-freeform-pro": "2.5.13",
    "craftcms/redactor": "2.3.2",
    "nystudio107/craft-typogrify": "1.1.16",
    "nystudio107/craft-cookies": "1.1.11",
    "rias/craft-position-fieldtype": "1.0.14",
    "barrelstrength/sprout-fields": "3.1.21",
    "craftcms/contact-form": "2.2.3",
    "rias/craft-contact-form-extensions": "1.1.1",
    "lukeyouell/craft-contactformtemplates": "1.0.1",
    "aelvan/craft-cp-element-count": "1.1.0",
    "craftcms/commerce": "2.1.0.2",
    "verbb/feed-me": "3.1.12",
    "verbb/feed-me-pro": "3.0.4",
    "doublesecretagency/craft-smartmap": "3.2.1",
    "ether/tags": "v1.0.0",
    "nystudio107/craft-eagerbeaver": "1.0.4",
    "nystudio107/craft-connect": "1.0.0",
    "craftcms/commerce-stripe": "1.0.10",
    "craftcms/commerce-paypal": "1.0.0.1",
    "aelvan/mailchimp-subscribe": "v2.0.4",
    "verbb/wishlist": "1.0.0",
    "nystudio107/craft-seomatic": "3.1.44",
    "superbig/craft-ordernotes": "2.0.1",
    "craftcms/aws-s3": "1.2.0",
    "craftcms/element-api": "2.5.4",
    "lukeyouell/craft-queue-manager": "1.1.0",
    "owldesign/qarr": "1.0.9",
    "doublesecretagency/craft-cpjs": "2.1.0",
    "doublesecretagency/craft-cpcss": "2.1.0",
    "verbb/field-manager": "2.0.5",
    "doublesecretagency/craft-cpbodyclasses": "2.1.0",
    "mmikkel/incognito-field": "1.1.1.1",
    "doublesecretagency/craft-viewcount": "1.0.0",
    "dukt/social": "2.0.0-beta.15",
    "mpdf/mpdf": "^7.1",
    "noxify/asset-ownership": "1.0.3",
    "nystudio107/craft-webperf": "1.0.3"
  },
  "autoload": {
    "psr-4": {
      "modules\\": "modules/"
    }
  },
  "config": {
    "optimize-autoloader": true,
    "platform": {
      "php": "7.0"
    }
  },
  "scripts": {
    "post-root-package-install": [
      "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
    ]
  },
  "minimum-stability": "dev",
  "prefer-stable": true,

**Comment by benjamindavid** [comment] 2019-03-05 08:58
It seems like some plugins are still using an older version of `league/oauth2-client`.

@john-henry The issue is related to Social LinkedIn, working on a fix for this one.

@xhuang9 Your issue doesn't seem to come from one of our plugins. I'm going to try with your `composer.json` to see what dependency is causing this.

**Comment by benjamindavid** [comment] 2019-03-05 10:22
@john-henry @xhuang9 In you `composer.json` file, can you please try to replace:
```"dukt/social": "2.0.0-beta.15",```

with this:
```"dukt/social": "^2.0",```

**Comment by john-henry** [comment] 2019-03-05 14:23
@benjamindavid I did so and ran update again but same error so maybe mine is specific to Social Linkedin as you say

**Comment by benjamindavid** [comment] 2019-03-05 15:15
@john-henry Pretty weird, I tested with your composer.json file without a problem. Could you please try to remove your `composer.lock` and `vendor/`, and then run:
````composer clearcache
composer install```
I’m thinking there could be some caching involved in this issue.

**Comment by xhuang9** [comment] 2019-03-05 23:10
Well, I tried
 ``` 
composer clearcache
composer install
```
It worked for me.

**Comment by bymayo** [comment] 2019-03-12 21:02
I also ran in to this issue. To fix it I just did `composer remove dukt/social` locally, then it removed Social and it's dependencies, then ran `composer require dukt/social` which pulled in the latest dependencies for `^2.0`.

Then pushing the updated `composer.lock` and deploying installed fine on production.

Bloody composer!

**Comment by john-henry** [comment] 2019-03-12 21:03
Bit of moving and shaking of composer got me sorted too thanks

**Comment by benjamindavid** [comment] 2019-03-12 21:18
Awesome, thanks for the feedback guys!

**Closed by benjamindavid** 2019-03-12 21:18 UTC
