### ISSUE TITLE
Facebook login throwing error when fb has profile image.

### ISSUE THREAD

**Issue by lettie16** [dukt/social#8] opened 2018-04-26 15:47 UTC
### Description
Facebook login throws error when facebook profile has image. Works ok when no image is in test user account.

### Steps to reproduce

1. Login with a facebook user who is a brand new user to craft and hasn't approved the app and has a profile image.

### Additional info

Error Message: Undefined variable: account
craft/plugins/social/controllers/SocialController.php(366)

- Plugin version: 1.2.5 & 1.2.6
- Craft version: 2.6.3015
- PHP version: 7.1.16
- Database driver & version: mysql 5.5
- Plugins & versions:

**Comment by benjamindavid** [comment] 2018-05-03 17:49
@lettie16 The `account` variable error should be fixed by https://github.com/dukt/social/commit/385065c3dc0224e16670cc8805f879c6ad51ab33. I can't reproduce the profile image error. What's your Facebook API version?

If the problem persists, feel free to reopen and check for related errors in your logs, in `craft/storage/runtime/logs`.

**Closed by benjamindavid** 2018-05-03 17:49 UTC
Labels: bug
